var dir_68267d1309a1af8e8297ef4c3efbcdba =
[
    [ "hangul.h", "hangul_8h.html", "hangul_8h" ],
    [ "hex2otf.c", "hex2otf_8c.html", "hex2otf_8c" ],
    [ "hex2otf.h", "hex2otf_8h.html", "hex2otf_8h" ],
    [ "johab2syllables.c", "johab2syllables_8c.html", "johab2syllables_8c" ],
    [ "unibdf2hex.c", "unibdf2hex_8c.html", "unibdf2hex_8c" ],
    [ "unibmp2hex.c", "unibmp2hex_8c.html", "unibmp2hex_8c" ],
    [ "unibmpbump.c", "unibmpbump_8c.html", "unibmpbump_8c" ],
    [ "unicoverage.c", "unicoverage_8c.html", "unicoverage_8c" ],
    [ "unidup.c", "unidup_8c.html", "unidup_8c" ],
    [ "unifont-support.c", "unifont-support_8c.html", "unifont-support_8c" ],
    [ "unifont1per.c", "unifont1per_8c.html", "unifont1per_8c" ],
    [ "unifontpic.c", "unifontpic_8c.html", "unifontpic_8c" ],
    [ "unifontpic.h", "unifontpic_8h.html", "unifontpic_8h" ],
    [ "unigen-hangul.c", "unigen-hangul_8c.html", "unigen-hangul_8c" ],
    [ "unigencircles.c", "unigencircles_8c.html", "unigencircles_8c" ],
    [ "unigenwidth.c", "unigenwidth_8c.html", "unigenwidth_8c" ],
    [ "unihangul-support.c", "unihangul-support_8c.html", "unihangul-support_8c" ],
    [ "unihex2bmp.c", "unihex2bmp_8c.html", "unihex2bmp_8c" ],
    [ "unihexgen.c", "unihexgen_8c.html", "unihexgen_8c" ],
    [ "unihexpose.c", "unihexpose_8c_source.html", null ],
    [ "unijohab2html.c", "unijohab2html_8c.html", "unijohab2html_8c" ],
    [ "unipagecount.c", "unipagecount_8c.html", "unipagecount_8c" ]
];